/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import MainNav from 'src/components/MainNav/MainNav';
import AppBar from 'src/components/AppBar/AppBar';
import Header from 'src/components/Header/Header';
import EntityContainer from 'src/components/EntityContainer/EntityContainer';
import { PageTemplatePrototypeProps } from 'src/types';

const StateNavOpened: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const PageTemplate: any = styled('div')(({ theme }: any) => ({
  backgroundColor: theme.palette['colors']['grey']['100'],
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `1080px`,
  width: `2048px`,
  margin: `0px`,
}));

const MainNav1: any = styled(MainNav)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const PageContainer: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Box1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
});

const AppBar1: any = styled(AppBar)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Header1: any = styled(Header)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Content: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
});

const EntityContainer1: any = styled(EntityContainer)(({ theme }: any) => ({
  height: `709px`,
  width: `1400px`,
  margin: `0px`,
}));

function PageTemplatePrototype(props: PageTemplatePrototypeProps): JSX.Element {
  return (
    <StateNavOpened className={props.className}>
      <PageTemplate>
        <MainNav1 />
        <PageContainer>
          <Box1>
            <AppBar1 />
            <Header1 />
            <Content>
              <EntityContainer1 />
            </Content>
          </Box1>
        </PageContainer>
      </PageTemplate>
    </StateNavOpened>
  );
}

export default PageTemplatePrototype;
