/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { colors } from '@mui/material';
import React, { useState } from 'react';
import { useTheme } from '@mui/material/styles';

const useEntityContainer = () => {
  const toggleEdit = (): any => {};
  const editButton = (): any => {
    return 'Edit';
  };

  const useButtonColor = (label: string) => {
    const theme = useTheme();
    return label === 'Edit'
      ? theme.palette['primary']
      : theme.palette['success'];
  };

  const [isEdit, setIsEdit] = useState(false);

  const data: any = { isEdit, editButton };

  const fns: any = {
    toggleEdit: () => setIsEdit(!isEdit),
  };

  return { data, fns };
};

export default useEntityContainer;
