/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { colors } from '@mui/material';
import React, { useState } from 'react';
import { useTheme } from '@mui/material/styles';

const useEntityContainer = () => {
  const toggleEdit = (): any => {};
  const editButton = (): any => {
    return 'Edit';
  };

  const [isEdit, setIsEdit] = useState(false);

  const useButtonVariant = (): any => {
    return (
      data.isEdit ? 'text' : 'disabled'
    );
  };

  const data: any = { isEdit, editButton, useButtonVariant };

  const fns: any = {
    toggleEdit: () => setIsEdit(!isEdit), toggleEdit
  };

  return { data, fns };
};

export default useEntityContainer;
